//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__quote_entry__(SB), NOSPLIT, $16
	NO_LOCAL_POINTERS
	WORD $0x100000a0 // adr x0, .+20
	MOVD R0, ret(FP)
	RET
	// .p2align 4, 0x00
	
DATA LCDATA1<>+0x000(SB)/8, $0x8040201008040201
DATA LCDATA1<>+0x008(SB)/8, $0x8040201008040201
DATA LCDATA1<>+0x010(SB)/8, $0x0b030a0209010800
DATA LCDATA1<>+0x018(SB)/8, $0x0f070e060d050c04
GLOBL LCDATA1<>(SB), 8, $32

LCPI0_0:
    WORD $0x08040201
    WORD $0x80402010
    WORD $0x08040201
    WORD $0x80402010
LCPI0_1:
    WORD $0x09010800
    WORD $0x0b030a02
    WORD $0x0d050c04
    WORD $0x0f070e06
quote:
    WORD $0xf81f0ffd // str    fp, [sp, #-16]!
    WORD $0x043f57ff // addvl    sp, sp, #-1
    WORD $0xf9400069 // ldr    x9, [x3]
    ADR _DoubleQuoteTab, R8
    WORD $0x91000108 // add    x8, x8, :lo12:_DoubleQuoteTab
    ADR _SingleQuoteTab, R10
    WORD $0x9100014a // add    x10, x10, :lo12:_SingleQuoteTab
    WORD $0xf240009f // tst    x4, #0x1
    WORD $0x9a880148 // csel    x8, x10, x8, eq
    WORD $0xeb010d3f // cmp    x9, x1, lsl #3
    BGE LBB0_88
    WORD $0xaa0203eb // mov    x11, x2
    WORD $0xaa0003ee // mov    x14, x0
    CMP $0, R1
    BEQ LBB0_117
    WORD $0x2518e3e0 // ptrue    p0.b
    WORD $0x4f01e440 // movi    v0.16b, #34
    WORD $0x4f02e781 // movi    v1.16b, #92
    WORD $0x4f01e402 // movi    v2.16b, #32
    ADR LCPI0_0, R11
    ADR LCPI0_1, R12
    WORD $0x2538c3e3 // mov    z3.b, #31
    WORD $0x2538c444 // mov    z4.b, #34
    WORD $0x3dc00166 // ldr    q6, [x11, :lo12:.LCPI0_0]
    WORD $0x2538cb85 // mov    z5.b, #92
    WORD $0x3dc00187 // ldr    q7, [x12, :lo12:.LCPI0_1]
    WORD $0xd100040c // sub    x12, x0, #1
    WORD $0xaa0003ed // mov    x13, x0
    WORD $0xaa0203eb // mov    x11, x2
    WORD $0xf1007c3f // cmp    x1, #31
    WORD $0x1a9fd7f1 // cset    w17, gt
    WORD $0xf100803f // cmp    x1, #32
    BGE LBB0_43
LBB0_3:
    WORD $0xaa0903f0 // mov    x16, x9
    WORD $0xaa0b03ef // mov    x15, x11
    WORD $0xaa0103f2 // mov    x18, x1
    WORD $0xaa0d03ee // mov    x14, x13
    TST $(1<<0), R17
    BNE LBB0_50
LBB0_4:
    WORD $0xf1003e5f // cmp    x18, #15
    WORD $0x1a9fd7e6 // cset    w6, gt
    WORD $0xf100425f // cmp    x18, #16
    BLT LBB0_14
    WORD $0xf100421f // cmp    x16, #16
    BLT LBB0_14
    WORD $0xcb0e01a5 // sub    x5, x13, x14
LBB0_7:
    WORD $0xa94019c4 // ldp    x4, x6, [x14]
    WORD $0x9e670090 // fmov    d16, x4
    WORD $0xa90019e4 // stp    x4, x6, [x15]
    WORD $0x4e181cd0 // mov    v16.d[1], x6
    WORD $0x6e208e11 // cmeq    v17.16b, v16.16b, v0.16b
    WORD $0x6e218e12 // cmeq    v18.16b, v16.16b, v1.16b
    WORD $0x6e303450 // cmhi    v16.16b, v2.16b, v16.16b
    WORD $0x4eb21e31 // orr    v17.16b, v17.16b, v18.16b
    WORD $0x4eb01e30 // orr    v16.16b, v17.16b, v16.16b
    WORD $0x4e261e10 // and    v16.16b, v16.16b, v6.16b
    WORD $0x4e070210 // tbl    v16.16b, { v16.16b }, v7.16b
    WORD $0x4e71ba10 // addv    h16, v16.8h
    WORD $0x1e260211 // fmov    w17, s16
    CMP $0, R17
    BNE LBB0_21
    WORD $0xf1007e5f // cmp    x18, #31
    WORD $0x910041ce // add    x14, x14, #16
    WORD $0x910041ef // add    x15, x15, #16
    WORD $0x1a9fd7e6 // cset    w6, gt
    WORD $0xf100825f // cmp    x18, #32
    WORD $0xd1004244 // sub    x4, x18, #16
    WORD $0xd1004211 // sub    x17, x16, #16
    BLT LBB0_10
    WORD $0xf1007e1f // cmp    x16, #31
    WORD $0xd10040a5 // sub    x5, x5, #16
    WORD $0xaa0403f2 // mov    x18, x4
    WORD $0xaa1103f0 // mov    x16, x17
    BGT LBB0_7
LBB0_10:
    TST $(1<<0), R6
    BEQ LBB0_15
LBB0_11:
    WORD $0x3dc001d0 // ldr    q16, [x14]
    WORD $0x6e208e11 // cmeq    v17.16b, v16.16b, v0.16b
    WORD $0x6e218e12 // cmeq    v18.16b, v16.16b, v1.16b
    WORD $0x6e303453 // cmhi    v19.16b, v2.16b, v16.16b
    WORD $0x9e660204 // fmov    x4, d16
    WORD $0x4eb21e31 // orr    v17.16b, v17.16b, v18.16b
    WORD $0x4eb31e31 // orr    v17.16b, v17.16b, v19.16b
    WORD $0x4e261e31 // and    v17.16b, v17.16b, v6.16b
    WORD $0x4e070231 // tbl    v17.16b, { v17.16b }, v7.16b
    WORD $0x4e71ba31 // addv    h17, v17.8h
    WORD $0x1e260230 // fmov    w16, s17
    WORD $0x32100210 // orr    w16, w16, #0x10000
    WORD $0x5ac00210 // rbit    w16, w16
    WORD $0x5ac01210 // clz    w16, w16
    WORD $0xeb10023f // cmp    x17, x16
    BGE LBB0_25
    WORD $0xf1002232 // subs    x18, x17, #8
    BLO LBB0_27
    WORD $0x910021d0 // add    x16, x14, #8
    WORD $0xf80085e4 // str    x4, [x15], #8
    B LBB0_28
LBB0_14:
    WORD $0xaa1003f1 // mov    x17, x16
    WORD $0xaa1203e4 // mov    x4, x18
    TST $(1<<0), R6
    BNE LBB0_11
LBB0_15:
    WORD $0xf100049f // cmp    x4, #1
    BLT LBB0_22
    WORD $0xf100063f // cmp    x17, #1
    BLT LBB0_22
    WORD $0xcb0d01d0 // sub    x16, x14, x13
LBB0_18:
    WORD $0x394001c5 // ldrb    w5, [x14]
    WORD $0xd37cecb2 // lsl    x18, x5, #4
    WORD $0xf8726952 // ldr    x18, [x10, x18]
    CMP $0, R18_PLATFORM
    BNE LBB0_64
    WORD $0xd1000492 // sub    x18, x4, #1
    WORD $0xf100089f // cmp    x4, #2
    WORD $0x910005ce // add    x14, x14, #1
    WORD $0x380015e5 // strb    w5, [x15], #1
    BLT LBB0_23
    WORD $0xf100063f // cmp    x17, #1
    WORD $0xd1000631 // sub    x17, x17, #1
    WORD $0x91000610 // add    x16, x16, #1
    WORD $0xaa1203e4 // mov    x4, x18
    BGT LBB0_18
    B LBB0_23
LBB0_21:
    WORD $0x5ac0022e // rbit    w14, w17
    WORD $0x5ac011ce // clz    w14, w14
    WORD $0xcb0501d0 // sub    x16, x14, x5
    TST $(1<<63), R16
    BEQ LBB0_65
    B LBB0_119
LBB0_22:
    WORD $0xaa0403f2 // mov    x18, x4
LBB0_23:
    CMP $0, R18_PLATFORM
    BNE LBB0_63
    WORD $0xcb0d01d0 // sub    x16, x14, x13
    TST $(1<<63), R16
    BEQ LBB0_65
    B LBB0_119
LBB0_25:
    WORD $0x7100221f // cmp    w16, #8
    BLO LBB0_35
    WORD $0x910021d1 // add    x17, x14, #8
    WORD $0xd1002212 // sub    x18, x16, #8
    WORD $0xf80085e4 // str    x4, [x15], #8
    B LBB0_36
LBB0_27:
    WORD $0xaa0e03f0 // mov    x16, x14
    WORD $0xaa1103f2 // mov    x18, x17
LBB0_28:
    WORD $0xf1001244 // subs    x4, x18, #4
    BLT LBB0_33
    WORD $0xb8404612 // ldr    w18, [x16], #4
    WORD $0xb80045f2 // str    w18, [x15], #4
    WORD $0xaa0403f2 // mov    x18, x4
    WORD $0xf1000884 // subs    x4, x4, #2
    BHS LBB0_34
LBB0_30:
    CMP $0, R18_PLATFORM
    BEQ LBB0_32
LBB0_31:
    WORD $0x39400210 // ldrb    w16, [x16]
    WORD $0x390001f0 // strb    w16, [x15]
LBB0_32:
    WORD $0x8b0e022e // add    x14, x17, x14
    B LBB0_63
LBB0_33:
    WORD $0xf1000a44 // subs    x4, x18, #2
    BLO LBB0_30
LBB0_34:
    WORD $0x78402612 // ldrh    w18, [x16], #2
    WORD $0x780025f2 // strh    w18, [x15], #2
    WORD $0xaa0403f2 // mov    x18, x4
    CMP $0, R4
    BNE LBB0_31
    B LBB0_32
LBB0_35:
    WORD $0xaa0e03f1 // mov    x17, x14
    WORD $0xaa1003f2 // mov    x18, x16
LBB0_36:
    WORD $0xf1001244 // subs    x4, x18, #4
    BLO LBB0_41
    WORD $0xb8404632 // ldr    w18, [x17], #4
    WORD $0xb80045f2 // str    w18, [x15], #4
    WORD $0xaa0403f2 // mov    x18, x4
    WORD $0xf1000884 // subs    x4, x4, #2
    BHS LBB0_42
LBB0_38:
    CMP $0, R18_PLATFORM
    BEQ LBB0_40
LBB0_39:
    WORD $0x39400231 // ldrb    w17, [x17]
    WORD $0x390001f1 // strb    w17, [x15]
LBB0_40:
    WORD $0xcb0d01ce // sub    x14, x14, x13
    WORD $0x8b1001d0 // add    x16, x14, x16
    TST $(1<<63), R16
    BEQ LBB0_65
    B LBB0_119
LBB0_41:
    WORD $0xf1000a44 // subs    x4, x18, #2
    BLO LBB0_38
LBB0_42:
    WORD $0x78402632 // ldrh    w18, [x17], #2
    WORD $0x780025f2 // strh    w18, [x15], #2
    WORD $0xaa0403f2 // mov    x18, x4
    CMP $0, R4
    BNE LBB0_39
    B LBB0_40
LBB0_43:
    WORD $0xf100813f // cmp    x9, #32
    WORD $0xaa0903f0 // mov    x16, x9
    WORD $0xaa0b03ef // mov    x15, x11
    WORD $0xaa0103f2 // mov    x18, x1
    WORD $0xaa0d03ee // mov    x14, x13
    BLT LBB0_49
    WORD $0xaa1f03f0 // mov    x16, xzr
    WORD $0xaa0d03ee // mov    x14, x13
    WORD $0xaa0b03ef // mov    x15, x11
LBB0_45:
    WORD $0xa400a1d0 // ld1b    { z16.b }, p0/z, [x14]
    WORD $0x047f50f1 // addpl    x17, sp, #7
    WORD $0x251f0211 // cmpgt    p1.b, p0/z, z16.b, #-1
    WORD $0x24038212 // cmpgt    p2.b, p0/z, z16.b, z3.b
    WORD $0x2404a203 // cmpeq    p3.b, p0/z, z16.b, z4.b
    WORD $0x2405a204 // cmpeq    p4.b, p0/z, z16.b, z5.b
    WORD $0x25024031 // bic    p1.b, p0/z, p1.b, p2.b
    WORD $0x25844062 // orr    p2.b, p0/z, p3.b, p4.b
    WORD $0x25824021 // orr    p1.b, p0/z, p1.b, p2.b
    WORD $0xe5801fe1 // str    p1, [sp, #7, mul vl]
    WORD $0xe400e1f0 // st1b    { z16.b }, p0, [x15]
    WORD $0xb9400231 // ldr    w17, [x17]
    CMP $0, R17
    BNE LBB0_53
    WORD $0x8b100032 // add    x18, x1, x16
    WORD $0x910081ce // add    x14, x14, #32
    WORD $0x910081ef // add    x15, x15, #32
    WORD $0xf100fe5f // cmp    x18, #63
    WORD $0xd1008204 // sub    x4, x16, #32
    WORD $0x1a9fd7f1 // cset    w17, gt
    WORD $0xf101025f // cmp    x18, #64
    BLT LBB0_48
    WORD $0x8b100130 // add    x16, x9, x16
    WORD $0xf100fe1f // cmp    x16, #63
    WORD $0xaa0403f0 // mov    x16, x4
    BGT LBB0_45
LBB0_48:
    WORD $0x8b040032 // add    x18, x1, x4
    WORD $0x8b040130 // add    x16, x9, x4
LBB0_49:
    TST $(1<<0), R17
    BEQ LBB0_4
LBB0_50:
    WORD $0xa400a1d0 // ld1b    { z16.b }, p0/z, [x14]
    WORD $0x047f50d1 // addpl    x17, sp, #6
    WORD $0x251f0211 // cmpgt    p1.b, p0/z, z16.b, #-1
    WORD $0x24038212 // cmpgt    p2.b, p0/z, z16.b, z3.b
    WORD $0x2404a203 // cmpeq    p3.b, p0/z, z16.b, z4.b
    WORD $0x2405a204 // cmpeq    p4.b, p0/z, z16.b, z5.b
    WORD $0x25024031 // bic    p1.b, p0/z, p1.b, p2.b
    WORD $0x25844062 // orr    p2.b, p0/z, p3.b, p4.b
    WORD $0x25824021 // orr    p1.b, p0/z, p1.b, p2.b
    WORD $0xe5801be1 // str    p1, [sp, #6, mul vl]
    WORD $0xb9400231 // ldr    w17, [x17]
    WORD $0xb2600231 // orr    x17, x17, #0x100000000
    WORD $0xdac00231 // rbit    x17, x17
    WORD $0xdac01231 // clz    x17, x17
    WORD $0xeb10023f // cmp    x17, x16
    BLE LBB0_54
    WORD $0xaa0e03f1 // mov    x17, x14
    WORD $0xf1004212 // subs    x18, x16, #16
    BLO LBB0_56
    WORD $0x3cc10630 // ldr    q16, [x17], #16
    WORD $0x3c8105f0 // str    q16, [x15], #16
    WORD $0xf1002244 // subs    x4, x18, #8
    BHS LBB0_57
    B LBB0_58
LBB0_53:
    WORD $0x5ac0022e // rbit    w14, w17
    WORD $0x5ac011ce // clz    w14, w14
    WORD $0xcb1001d0 // sub    x16, x14, x16
    TST $(1<<63), R16
    BEQ LBB0_65
    B LBB0_119
LBB0_54:
    WORD $0xaa0e03f0 // mov    x16, x14
    WORD $0xf1004232 // subs    x18, x17, #16
    BLO LBB0_79
    WORD $0x3cc10610 // ldr    q16, [x16], #16
    WORD $0x3c8105f0 // str    q16, [x15], #16
    WORD $0xf1002244 // subs    x4, x18, #8
    BHS LBB0_80
    B LBB0_81
LBB0_56:
    WORD $0xaa1003f2 // mov    x18, x16
    WORD $0xf1002204 // subs    x4, x16, #8
    BLO LBB0_58
LBB0_57:
    WORD $0xf8408632 // ldr    x18, [x17], #8
    WORD $0xf80085f2 // str    x18, [x15], #8
    WORD $0xaa0403f2 // mov    x18, x4
LBB0_58:
    WORD $0xf1001244 // subs    x4, x18, #4
    BLT LBB0_77
    WORD $0xb8404632 // ldr    w18, [x17], #4
    WORD $0xb80045f2 // str    w18, [x15], #4
    WORD $0xaa0403f2 // mov    x18, x4
    WORD $0xf1000884 // subs    x4, x4, #2
    BHS LBB0_78
LBB0_60:
    CMP $0, R18_PLATFORM
    BEQ LBB0_62
LBB0_61:
    WORD $0x39400231 // ldrb    w17, [x17]
    WORD $0x390001f1 // strb    w17, [x15]
LBB0_62:
    WORD $0x8b0e020e // add    x14, x16, x14
LBB0_63:
    WORD $0xaa2e03ee // mvn    x14, x14
    WORD $0x8b0d01d0 // add    x16, x14, x13
LBB0_64:
    TST $(1<<63), R16
    BNE LBB0_119
LBB0_65:
    WORD $0xeb100021 // subs    x1, x1, x16
    WORD $0x8b1001ae // add    x14, x13, x16
    WORD $0x8b10016b // add    x11, x11, x16
    BEQ LBB0_117
    WORD $0x8b0d020d // add    x13, x16, x13
    WORD $0xcb100129 // sub    x9, x9, x16
    WORD $0xcb0d018d // sub    x13, x12, x13
    B LBB0_68
LBB0_67:
    WORD $0xd1000421 // sub    x1, x1, #1
    WORD $0x910005ce // add    x14, x14, #1
    WORD $0x8b0f016b // add    x11, x11, x15
    WORD $0xd10005ad // sub    x13, x13, #1
    CMP $0, R1
    BEQ LBB0_117
LBB0_68:
    WORD $0x394001cf // ldrb    w15, [x14]
    WORD $0x8b0f1111 // add    x17, x8, x15, lsl #4
    WORD $0xb940022f // ldr    w15, [x17]
    CMP $0, R15
    BEQ LBB0_76
    WORD $0x93407def // sxtw    x15, w15
    WORD $0xeb0f0129 // subs    x9, x9, x15
    BLT LBB0_118
    WORD $0xf10011f2 // subs    x18, x15, #4
    BLT LBB0_72
    WORD $0xb9400a24 // ldr    w4, [x17, #8]
    WORD $0xaa0b03f0 // mov    x16, x11
    WORD $0x91003231 // add    x17, x17, #12
    WORD $0xb8004604 // str    w4, [x16], #4
    WORD $0xf1000a44 // subs    x4, x18, #2
    BHS LBB0_73
    B LBB0_74
LBB0_72:
    WORD $0x91002231 // add    x17, x17, #8
    WORD $0xaa0b03f0 // mov    x16, x11
    WORD $0xaa0f03f2 // mov    x18, x15
    WORD $0xf10009e4 // subs    x4, x15, #2
    BLO LBB0_74
LBB0_73:
    WORD $0x78402632 // ldrh    w18, [x17], #2
    WORD $0x78002612 // strh    w18, [x16], #2
    WORD $0xaa0403f2 // mov    x18, x4
LBB0_74:
    CMP $0, R18_PLATFORM
    BEQ LBB0_67
    WORD $0x39400231 // ldrb    w17, [x17]
    WORD $0x39000211 // strb    w17, [x16]
    B LBB0_67
LBB0_76:
    WORD $0xaa0e03ed // mov    x13, x14
    WORD $0xf1007c3f // cmp    x1, #31
    WORD $0x1a9fd7f1 // cset    w17, gt
    WORD $0xf100803f // cmp    x1, #32
    BGE LBB0_43
    B LBB0_3
LBB0_77:
    WORD $0xf1000a44 // subs    x4, x18, #2
    BLO LBB0_60
LBB0_78:
    WORD $0x78402632 // ldrh    w18, [x17], #2
    WORD $0x780025f2 // strh    w18, [x15], #2
    WORD $0xaa0403f2 // mov    x18, x4
    CMP $0, R4
    BNE LBB0_61
    B LBB0_62
LBB0_79:
    WORD $0xaa1103f2 // mov    x18, x17
    WORD $0xf1002224 // subs    x4, x17, #8
    BLO LBB0_81
LBB0_80:
    WORD $0xf8408612 // ldr    x18, [x16], #8
    WORD $0xf80085f2 // str    x18, [x15], #8
    WORD $0xaa0403f2 // mov    x18, x4
LBB0_81:
    WORD $0xf1001244 // subs    x4, x18, #4
    BLO LBB0_86
    WORD $0xb8404612 // ldr    w18, [x16], #4
    WORD $0xb80045f2 // str    w18, [x15], #4
    WORD $0xaa0403f2 // mov    x18, x4
    WORD $0xf1000884 // subs    x4, x4, #2
    BHS LBB0_87
LBB0_83:
    CMP $0, R18_PLATFORM
    BEQ LBB0_85
LBB0_84:
    WORD $0x39400210 // ldrb    w16, [x16]
    WORD $0x390001f0 // strb    w16, [x15]
LBB0_85:
    WORD $0xcb0d01ce // sub    x14, x14, x13
    WORD $0x8b1101d0 // add    x16, x14, x17
    TST $(1<<63), R16
    BEQ LBB0_65
    B LBB0_119
LBB0_86:
    WORD $0xf1000a44 // subs    x4, x18, #2
    BLO LBB0_83
LBB0_87:
    WORD $0x78402612 // ldrh    w18, [x16], #2
    WORD $0x780025f2 // strh    w18, [x15], #2
    WORD $0xaa0403f2 // mov    x18, x4
    CMP $0, R4
    BNE LBB0_84
    B LBB0_85
LBB0_88:
    WORD $0x2518e3e0 // ptrue    p0.b
    WORD $0x4f01e442 // movi    v2.16b, #34
    WORD $0x4f02e783 // movi    v3.16b, #92
    WORD $0x4f01e404 // movi    v4.16b, #32
    ADR LCPI0_0, R10
    ADR LCPI0_1, R11
    WORD $0x2538c3e0 // mov    z0.b, #31
    WORD $0x2538c441 // mov    z1.b, #34
    WORD $0x3dc00146 // ldr    q6, [x10, :lo12:.LCPI0_0]
    WORD $0x2538cb85 // mov    z5.b, #92
    WORD $0x3dc00167 // ldr    q7, [x11, :lo12:.LCPI0_1]
    ADR _EscTab, R9
    WORD $0x91000129 // add    x9, x9, :lo12:_EscTab
    WORD $0xaa0203ea // mov    x10, x2
    WORD $0xaa0103ec // mov    x12, x1
LBB0_89:
    WORD $0xf100419f // cmp    x12, #16
    BGE LBB0_91
    WORD $0xaa0c03eb // mov    x11, x12
    B LBB0_99
LBB0_91:
    WORD $0xf100819f // cmp    x12, #32
    BLO LBB0_95
LBB0_92:
    WORD $0xa400a010 // ld1b    { z16.b }, p0/z, [x0]
    WORD $0x047f50ab // addpl    x11, sp, #5
    WORD $0x251f0211 // cmpgt    p1.b, p0/z, z16.b, #-1
    WORD $0x24008212 // cmpgt    p2.b, p0/z, z16.b, z0.b
    WORD $0x2401a203 // cmpeq    p3.b, p0/z, z16.b, z1.b
    WORD $0x2405a204 // cmpeq    p4.b, p0/z, z16.b, z5.b
    WORD $0x25024031 // bic    p1.b, p0/z, p1.b, p2.b
    WORD $0x25844062 // orr    p2.b, p0/z, p3.b, p4.b
    WORD $0x25824021 // orr    p1.b, p0/z, p1.b, p2.b
    WORD $0xe58017e1 // str    p1, [sp, #5, mul vl]
    WORD $0xe400e150 // st1b    { z16.b }, p0, [x10]
    WORD $0xb940016b // ldr    w11, [x11]
    CMP $0, R11
    BNE LBB0_109
    WORD $0xd100818b // sub    x11, x12, #32
    WORD $0xf100fd9f // cmp    x12, #63
    WORD $0x91008000 // add    x0, x0, #32
    WORD $0x9100814a // add    x10, x10, #32
    WORD $0xaa0b03ec // mov    x12, x11
    BHI LBB0_92
    WORD $0xf100417f // cmp    x11, #16
    BHS LBB0_96
    B LBB0_99
LBB0_95:
    WORD $0xaa0c03eb // mov    x11, x12
LBB0_96:
    WORD $0xaa0b03ec // mov    x12, x11
LBB0_97:
    WORD $0xa940380d // ldp    x13, x14, [x0]
    WORD $0x9e6701b0 // fmov    d16, x13
    WORD $0xa900394d // stp    x13, x14, [x10]
    WORD $0x4e181dd0 // mov    v16.d[1], x14
    WORD $0x6e228e11 // cmeq    v17.16b, v16.16b, v2.16b
    WORD $0x6e238e12 // cmeq    v18.16b, v16.16b, v3.16b
    WORD $0x6e303490 // cmhi    v16.16b, v4.16b, v16.16b
    WORD $0x4eb21e31 // orr    v17.16b, v17.16b, v18.16b
    WORD $0x4eb01e30 // orr    v16.16b, v17.16b, v16.16b
    WORD $0x4e261e10 // and    v16.16b, v16.16b, v6.16b
    WORD $0x4e070210 // tbl    v16.16b, { v16.16b }, v7.16b
    WORD $0x4e71ba10 // addv    h16, v16.8h
    WORD $0x1e26020b // fmov    w11, s16
    CMP $0, R11
    BNE LBB0_109
    WORD $0xd100418b // sub    x11, x12, #16
    WORD $0xf1007d9f // cmp    x12, #31
    WORD $0x91004000 // add    x0, x0, #16
    WORD $0x9100414a // add    x10, x10, #16
    WORD $0xaa0b03ec // mov    x12, x11
    BHI LBB0_97
LBB0_99:
    WORD $0xf100216c // subs    x12, x11, #8
    BLT LBB0_103
    WORD $0x3940000d // ldrb    w13, [x0]
    WORD $0x3940040e // ldrb    w14, [x0, #1]
    WORD $0x3940080f // ldrb    w15, [x0, #2]
    WORD $0x386d692d // ldrb    w13, [x9, x13]
    WORD $0x386e692e // ldrb    w14, [x9, x14]
    WORD $0x2a0e05ad // orr    w13, w13, w14, lsl #1
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x39400c0f // ldrb    w15, [x0, #3]
    WORD $0x2a0e09ad // orr    w13, w13, w14, lsl #2
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x2a0e0dad // orr    w13, w13, w14, lsl #3
    WORD $0xf940000e // ldr    x14, [x0]
    WORD $0x72001dbf // tst    w13, #0xff
    WORD $0xf900014e // str    x14, [x10]
    BNE LBB0_113
    WORD $0x3940100d // ldrb    w13, [x0, #4]
    WORD $0x3940140e // ldrb    w14, [x0, #5]
    WORD $0x3940180f // ldrb    w15, [x0, #6]
    WORD $0x386d692d // ldrb    w13, [x9, x13]
    WORD $0x386e692e // ldrb    w14, [x9, x14]
    WORD $0x2a0e05ad // orr    w13, w13, w14, lsl #1
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x39401c0f // ldrb    w15, [x0, #7]
    WORD $0x2a0e09ad // orr    w13, w13, w14, lsl #2
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x2a0e0dad // orr    w13, w13, w14, lsl #3
    WORD $0x72001dbf // tst    w13, #0xff
    BNE LBB0_114
    WORD $0x9100214a // add    x10, x10, #8
    WORD $0x91002000 // add    x0, x0, #8
    WORD $0xaa0c03eb // mov    x11, x12
LBB0_103:
    WORD $0xf100116c // subs    x12, x11, #4
    BLT LBB0_106
    WORD $0x3940000d // ldrb    w13, [x0]
    WORD $0x3940040e // ldrb    w14, [x0, #1]
    WORD $0x3940080f // ldrb    w15, [x0, #2]
    WORD $0x386d692d // ldrb    w13, [x9, x13]
    WORD $0x386e692e // ldrb    w14, [x9, x14]
    WORD $0x2a0e05ad // orr    w13, w13, w14, lsl #1
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x39400c0f // ldrb    w15, [x0, #3]
    WORD $0x2a0e09ad // orr    w13, w13, w14, lsl #2
    WORD $0x386f692e // ldrb    w14, [x9, x15]
    WORD $0x2a0e0dad // orr    w13, w13, w14, lsl #3
    WORD $0xb940000e // ldr    w14, [x0]
    WORD $0x72001dbf // tst    w13, #0xff
    WORD $0xb900014e // str    w14, [x10]
    BNE LBB0_113
    WORD $0x9100114a // add    x10, x10, #4
    WORD $0x91001000 // add    x0, x0, #4
    WORD $0xaa0c03eb // mov    x11, x12
LBB0_106:
    WORD $0xf100057f // cmp    x11, #1
    BLT LBB0_116
LBB0_107:
    WORD $0x3940000c // ldrb    w12, [x0]
    WORD $0x386c692d // ldrb    w13, [x9, x12]
    CMP $0, R13
    BNE LBB0_110
    WORD $0xf100056b // subs    x11, x11, #1
    WORD $0x91000400 // add    x0, x0, #1
    WORD $0x3800154c // strb    w12, [x10], #1
    BGT LBB0_107
    B LBB0_116
LBB0_109:
    WORD $0x5ac0016b // rbit    w11, w11
    WORD $0x5ac0116d // clz    w13, w11
    WORD $0x8b0d0000 // add    x0, x0, x13
    WORD $0xcb0d018b // sub    x11, x12, x13
    WORD $0x8b0d014a // add    x10, x10, x13
LBB0_110:
    WORD $0x3940000d // ldrb    w13, [x0]
    WORD $0xaa0b03ec // mov    x12, x11
LBB0_111:
    WORD $0x8b0d110b // add    x11, x8, x13, lsl #4
    WORD $0xf100099f // cmp    x12, #2
    WORD $0xb980016d // ldrsw    x13, [x11]
    WORD $0xf940056b // ldr    x11, [x11, #8]
    WORD $0xf900014b // str    x11, [x10]
    WORD $0x8b0d014a // add    x10, x10, x13
    BLT LBB0_116
    WORD $0x38401c0d // ldrb    w13, [x0, #1]!
    WORD $0xd100058c // sub    x12, x12, #1
    WORD $0x386d692b // ldrb    w11, [x9, x13]
    CMP $0, R11
    BNE LBB0_111
    B LBB0_89
LBB0_113:
    WORD $0x5ac001ac // rbit    w12, w13
    WORD $0x5ac0118c // clz    w12, w12
    B LBB0_115
LBB0_114:
    WORD $0x5ac001ac // rbit    w12, w13
    WORD $0x5ac0118c // clz    w12, w12
    WORD $0x1100118c // add    w12, w12, #4
LBB0_115:
    WORD $0x8b0c0000 // add    x0, x0, x12
    WORD $0xcb0c016b // sub    x11, x11, x12
    WORD $0x8b0c014a // add    x10, x10, x12
    B LBB0_110
LBB0_116:
    WORD $0xcb020148 // sub    x8, x10, x2
    WORD $0xf9000068 // str    x8, [x3]
    WORD $0xaa0103e0 // mov    x0, x1
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
LBB0_117:
    WORD $0xcb020168 // sub    x8, x11, x2
    WORD $0xcb0001c1 // sub    x1, x14, x0
    WORD $0xf9000068 // str    x8, [x3]
    WORD $0xaa0103e0 // mov    x0, x1
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
LBB0_118:
    WORD $0xcb020168 // sub    x8, x11, x2
    WORD $0xaa0d03e1 // mov    x1, x13
    WORD $0xf9000068 // str    x8, [x3]
    WORD $0xaa0103e0 // mov    x0, x1
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
LBB0_119:
    WORD $0x8b020208 // add    x8, x16, x2
    WORD $0xcb0d0009 // sub    x9, x0, x13
    WORD $0xaa2803e8 // mvn    x8, x8
    WORD $0x8b100121 // add    x1, x9, x16
    WORD $0x8b0b0108 // add    x8, x8, x11
    WORD $0xf9000068 // str    x8, [x3]
    WORD $0xaa0103e0 // mov    x0, x1
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
_SingleQuoteTab:
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003030
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003130
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003230
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003330
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003430
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003530
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003630
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003730
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003830
    WORD $0x00000002; WORD $0x00000000
    WORD $0x0000745C
    WORD $0x00000000
    WORD $0x00000002; WORD $0x00000000
    WORD $0x00006E5C
    WORD $0x00000000
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006230
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006330
    WORD $0x00000002; WORD $0x00000000
    WORD $0x0000725C
    WORD $0x00000000
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006530
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006630
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003031
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003131
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003231
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003331
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003431
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003531
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003631
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003731
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003831
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00003931
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006131
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006231
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006331
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006431
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006531
    WORD $0x00000006; WORD $0x00000000
    WORD $0x3030755C
    WORD $0x00006631
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000002; WORD $0x00000000
    WORD $0x0000225C
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000002; WORD $0x00000000
    WORD $0x00005C5C
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
_DoubleQuoteTab:
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00303030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00313030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00323030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00333030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00343030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00353030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00363030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00373030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00383030
    WORD $0x00000003; WORD $0x00000000
    WORD $0x00745C5C
    WORD $0x00000000
    WORD $0x00000003; WORD $0x00000000
    WORD $0x006E5C5C
    WORD $0x00000000
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00623030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00633030
    WORD $0x00000003; WORD $0x00000000
    WORD $0x00725C5C
    WORD $0x00000000
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00653030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00663030
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00303130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00313130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00323130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00333130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00343130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00353130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00363130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00373130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00383130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00393130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00613130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00623130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00633130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00643130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00653130
    WORD $0x00000007; WORD $0x00000000
    WORD $0x30755C5C
    WORD $0x00663130
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000004; WORD $0x00000000
    WORD $0x225C5C5C
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000004; WORD $0x00000000
    WORD $0x5C5C5C5C
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
_EscTab:
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x01010101
    WORD $0x00010000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000001
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000
    WORD $0x00000000

TEXT ·__quote(SB), NOSPLIT, $0-48
	NO_LOCAL_POINTERS

_entry:
	MOVD 16(g), R16
	SUB $96, RSP, R17
	CMP  R16, R17
	BLS  _stack_grow

_quote:
	MOVD sp+0(FP), R0
	MOVD nb+8(FP), R1
	MOVD dp+16(FP), R2
	MOVD dn+24(FP), R3
	MOVD flags+32(FP), R4
	MOVD ·_subr__quote(SB), R11
	WORD $0x1000005e // adr x30, .+8
	JMP (R11)
	MOVD R0, ret+40(FP)
	RET

_stack_grow:
	MOVD R30, R3
	CALL runtime·morestack_noctxt<>(SB)
	JMP  _entry
